### PR TITLE
QA - Css

### PR DESCRIPTION
**Pull request by afong888**
Edited css links and naming conventions

Changed question entry to account for when there are no questions

### CODE REVIEW

**Comment by afong888** [comment]
@kyang9021 could you please do this code review? Thank you!

**Comment by kyang9021** [comment]
@afong888 Could you fix the merge conflicts

**Comment by kyang9021** [comment]
@afong888 Site currently crashes, I believe you merged the wrong changes

**Comment by kyang9021** [comment]
Looks GTM!

**Pull request merged**
