### PR TITLE
Review modal

### PR DESCRIPTION
**Pull request by kyang9021**
@r-jeng  Can you code review this when you've got the time

### CODE REVIEW

**Comment by r-jeng** [comment]
@kyang9021 Could you help resolve the merge conflicts?

**Comment by r-jeng** [comment]
Picking up now!

**Comment by kyang9021** [comment]
@r-jeng Done!

**Review by r-jeng — APPROVED** [review]
Don't forget to add asterisks next to the titles that are mandatory. Otherwise everything looks great. Awesome job on the modal and stars!

**Pull request merged**
